### ISSUE TITLE
`_container.exec(["mkdir"...` vs `_container.make_dir()`

### ISSUE THREAD

**Issue by Abuelodelanada** [canonical/loki-operator#38]
https://github.com/canonical/loki-operator/pull/33#discussion_r752730866

iirc when the dir is already created an exception is raised.

**Comment by simskij** [comment]
setting [this](https://github.com/canonical/operator/blob/0e98016ba9209be29ad6eb38a0cbe095bc038389/ops/model.py#L1272) to `True` seems to be equivalent to `-p`
